apiVersion: v1
kind: ResourceQuota
metadata:
  name: store-quota
  namespace: store-{{ .Values.storeId }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
    persistentvolumeclaims: {{ .Values.quota.pvcCount | quote }}
